version: '3.9'
services:
  redis:
    image: redis:7.0.5-alpine
    restart: always
    ports:
      - "6379:6379"
    environment:
      ALLOW_EMPTY_POSSWORD: yes
  mongodb:
    image: mongo:5.0
    restart: always
    ports:
      - "27017:27017"
    environment:
      MONGO_INITTDB_ROOT_USERNAME: root
      MONGO_INITTDB_ROOT_PASSWORD: root

networks:
  chat-ws-redis: