package com.chat.ws.providers;

import org.junit.jupiter.api.Test;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.boot.test.context.SpringBootTest;

import java.util.Map;

@SpringBootTest
public class JsonWebTokenProviderTest {
    @Autowired
    private TokenProvider tokenProvider;

    @Test
    void test(){
        Map<String, String> decoded = tokenProvider.decode("eyJhbGciOiJSUzI1NiIsInR5cCI6IkpXVCIsImtpZCI6Im05MHdSUU0zVEJBb1Z1VWtyX09wdyJ9.eyJnaXZlbl9uYW1lIjoiRGFuaWVsIiwiZmFtaWx5X25hbWUiOiJGYWxjYW8iLCJuaWNrbmFtZSI6ImRhbmllbGZhbGNhby5kZiIsIm5hbWUiOiJEYW5pZWwgRmFsY2FvIiwicGljdHVyZSI6Imh0dHBzOi8vbGgzLmdvb2dsZXVzZXJjb250ZW50LmNvbS9hL0FBY0hUdGZhT3hsd1NWNndFRUZ4LTNJRmNZRnVsa3llVTdOOFBWUy1zWmFwREtidWtvWT1zOTYtYyIsImxvY2FsZSI6InB0LUJSIiwidXBkYXRlZF9hdCI6IjIwMjMtMDctMjhUMTc6NTA6NTkuMzU2WiIsImVtYWlsIjoiZGFuaWVsZmFsY2FvLmRmQGdtYWlsLmNvbSIsImVtYWlsX3ZlcmlmaWVkIjp0cnVlLCJpc3MiOiJodHRwczovL2RldmZhbGNhby51cy5hdXRoMC5jb20vIiwiYXVkIjoiU2FzWGpQOU41UUFOeXB3c1BSQjQ2dFdkbk81N0ZibzEiLCJpYXQiOjE2OTA1NjY2NjAsImV4cCI6MTY5MDYwMjY2MCwic3ViIjoiZ29vZ2xlLW9hdXRoMnwxMDAxMDM0NDU5MTYzODQyMjA4ODMiLCJzaWQiOiJqeFM2SXVQWGp3QXBKUkg2azJzUFBHbndWcHZSc1VhNSIsIm5vbmNlIjoiTm1WeVpHTjNXRVJuUm5CWFMwNXRUWHA1VkVSaVJHSmliVVUwYzM1T2VVNTNWMkpTYjFkaVJrMTRWdz09In0.CD5pXpt9WHzsldwWD8o3WZuoiX5FPSS_RWEy0Gwmv_42ikOuOv9pNye0F58frnYSACVc4HIHiIU_fJdVF9VJVcQ06Qv3c9e1ebyrd4WpedWIExSkKGvKd_LtGthhAlUyrgGOxc8HgjfxAl_qmCVZdjxrfXfLo7TOJ8VQyc5GDHcqK5vL8UCC2qkPsVBHkKSJLGHCjD-vN_pE6wkB3KEXMXcFW9-WTjpXJHcQWLbpFjmvMMPgmEOm9jvEUCVlrRpb54MgoRDCBHGCESPSVoPUI2uFd-8nfNcFL4H7kToYkwnCiJtc5-edG4HLInBONdcgQ8C0etMspbnacTTY2CkubQ");
        System.out.println(decoded);
    }
}
